import type { LegalDocument } from './types'

export const terms: LegalDocument = {
    title: 'Terms of Service',
    summary:
        'These terms cover the hosted Agent Room service while it is in early access. They are written in plain English so you can understand what you are agreeing to before you rely on the product.',
    updated: 'June 9, 2026',
    sections: [
        {
            heading: 'Hosted service and acceptance',
            body: [
                'Agent Room is software for deploying isolated AI rooms, where each room behaves like a separate AI coworker with its own identity, memory, workspace filesystem, generated artifacts, tools, scheduled jobs, model binding, and credentials. The hosted service runs and maintains this infrastructure on your behalf so you do not have to operate it yourself.',
                'These terms apply to the hosted service that we operate while it is in early access. By creating an account, joining the waitlist, or otherwise accessing the hosted service, you agree to these terms. Material updates will be published on this page. If you are accepting on behalf of a company or other organization, you confirm that you are authorized to bind that organization to these terms.',
            ],
        },
        {
            heading: 'Eligibility and accounts',
            body: [
                'You must be able to form a binding contract to use the hosted service, and you must provide accurate account information and keep it current. We may decline, suspend, or close accounts that appear to violate these terms or that we are unable to verify.',
                'During early access, availability is limited and access may be granted, paused, or revoked at our discretion as we manage capacity. We will make a reasonable effort to give notice before closing an active account that is in good standing.',
            ],
        },
        {
            heading: 'Acceptable use',
            body: [
                'You agree not to use the hosted service for anything illegal, harmful, or abusive, and not to use it to generate or distribute content that violates applicable law or the rights of others.',
                'You agree not to attempt to break room isolation, access another tenant or customer, interfere with or degrade the service for others, or circumvent security, rate limits, or access controls. You also agree not to abuse, probe, or attempt to extract the isolation boundaries, credentials, or secrets associated with rooms that are not yours.',
                'You are responsible for ensuring that your use of tools available to rooms, including bash execution, web search, browser use, URL fetch, and connected MCP integrations, complies with applicable law and the terms of any system or service those tools reach.',
            ],
        },
        {
            heading: 'Account responsibility',
            body: [
                'You are responsible for keeping your account credentials safe and for all activity that occurs in your account and your rooms. If you believe your account or any room credential has been compromised, you should notify us promptly so we can help secure it.',
                'Because each room can run tools, scheduled recurring jobs, and provider calls on your behalf, you are responsible for reviewing what your rooms are configured to do. You should treat room configuration, connected tools, and scheduled jobs as actions taken under your authority.',
            ],
        },
        {
            heading: 'AI and provider usage',
            body: [
                'AI output in Agent Room is generated by third-party model providers that you select and bind per room. We do not author, control, or guarantee that output. Output may be inaccurate, incomplete, outdated, or otherwise unsuitable for your purpose, and you are responsible for reviewing and verifying it before relying on it.',
                'The hosted service provides no warranty that AI output is correct, safe, or fit for any particular use. You should not treat AI output as professional advice, and you should apply appropriate human review for any consequential decision.',
                'Where you provide your own provider keys or credentials, we use them as configured for the specific room you bind them to, in order to make calls to that provider on your behalf. Your use of a given provider is also subject to that provider terms, and you are responsible for maintaining the rights and entitlements needed to use it.',
            ],
        },
        {
            heading: 'Credits and billing',
            body: [
                'Pricing is not finalized. We expect the hosted service to use a subscription plus model credits or top-ups, but the structure and amounts are still being decided.',
                'There is no billing during the current early-access stage, and you will not be charged until a billing system exists, pricing is published, and you have agreed to it. We will not begin charging an account without first presenting the applicable terms and obtaining your agreement.',
            ],
        },
        {
            heading: 'Service availability',
            body: [
                'The hosted service is in early access and is provided without an uptime guarantee. Features may change, be added, or be removed, and the service may be unavailable for maintenance, capacity, or operational reasons.',
                'We will make reasonable efforts to keep the service running and to communicate significant disruptions, but you should not rely on the early-access service for time-critical or mission-critical workloads without your own safeguards.',
            ],
        },
        {
            heading: 'Self-hosted and source disclaimer',
            body: [
                'Agent Room source is open source and can be self-hosted for free. The open source software is provided as-is under its applicable license, and these hosted terms do not extend any warranty or service commitment to self-hosted deployments.',
                'If you self-host, operating, securing, updating, and maintaining your deployment is your own responsibility, and we are not responsible for the configuration, security, or behavior of infrastructure that you run yourself.',
            ],
        },
        {
            heading: 'Intellectual property',
            body: [
                'We and our licensors retain all rights in the hosted service, including its branding, interfaces, and non-open-source components. The open source portions of Agent Room are governed by their own license terms.',
                'You retain your rights in the content, files, and artifacts you create in your rooms. You grant us the limited rights needed to operate the hosted service for you, such as storing, processing, and transmitting your content to deliver the features you use, including sending content to the model provider you bind per room.',
            ],
        },
        {
            heading: 'Limitation of liability',
            body: [
                'To the maximum extent permitted by law, the hosted service is provided on an as-is and as-available basis without warranties of any kind, and we are not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data, profits, or business arising from your use of the service or from AI output.',
                'Because the service is in early access and currently provided without charge, our aggregate liability is limited to the greatest extent permitted by applicable law. Some jurisdictions do not allow certain limitations, so some of these limitations may not apply to you.',
            ],
        },
        {
            heading: 'Changes to terms',
            body: [
                'We may update these terms as the product develops and especially as it moves out of early access. When we make material changes, we will update the date on this page and, where appropriate, provide additional notice.',
                'Your continued use of the hosted service after an update takes effect means you accept the updated terms. If you do not agree, you should stop using the hosted service.',
            ],
        },
        {
            heading: 'Contact',
            body: [
                'If you have questions about these terms or how they apply to your account, please reach out through the contact channel listed on the marketing site. We will respond as our early-access capacity allows.',
            ],
        },
    ],
}

export const privacy: LegalDocument = {
    title: 'Privacy Policy',
    summary:
        'This policy explains what data the hosted Agent Room service handles and how we treat it. It is written in plain English and reflects the early-access stage of the product.',
    updated: 'June 9, 2026',
    sections: [
        {
            heading: 'Scope and overview',
            body: [
                'This policy covers the hosted Agent Room service that we operate during early access. It describes the categories of data we handle to run the service, why we handle them, and the choices available to you. Material changes will be published on this page.',
                'Agent Room runs isolated AI rooms, where each room has its own identity, memory, workspace filesystem, artifacts, tools, scheduled jobs, model binding, and credentials. Much of the data we handle exists to keep those rooms isolated and to operate them on your behalf.',
            ],
        },
        {
            heading: 'Account data',
            body: [
                'When you join the waitlist or create an account, we collect basic account data such as your name, email address, and company or organization name where provided. We use this to communicate with you, manage access during early access, and operate your account.',
                'We use your email to send service-related messages, such as access updates and important notices. We aim to keep marketing communication minimal and to honor opt-out requests.',
            ],
        },
        {
            heading: 'Workspace, room, and artifact data',
            body: [
                'When you use a room, you create content within it, including files in the room workspace filesystem, generated artifacts, and the room memory and history. We store and process this content to provide the room and its features to you.',
                'Content created in one room is scoped to that room as part of its isolation model. We handle this content to operate the service you have asked for, not to repurpose it for unrelated uses.',
            ],
        },
        {
            heading: 'Provider credentials and customer-provided secrets',
            body: [
                'When you provide provider keys, credentials, or other secrets, we bind them to the specific room you configure them for. They are used to make the provider and tool calls that room is set up to perform.',
                'Secrets are scoped to the room they belong to and are not shared or reused across other rooms or tenants. We aim to limit exposure of secrets to what is required to run the room they are bound to, and we store them with the protections described in the data security section below.',
            ],
        },
        {
            heading: 'Usage and telemetry',
            body: [
                'To operate and improve the service, we handle usage data such as tool execution history, run and runtime state, scheduled job activity, and token and cost telemetry associated with provider usage.',
                'This data helps us deliver per-room audit and usage trails, debug issues, manage capacity, and understand how the service performs. We aim to keep telemetry focused on operating the service rather than on profiling you.',
            ],
        },
        {
            heading: 'Third-party model providers',
            body: [
                'AI output is generated by third-party model providers that you bind per room. When a room runs, the relevant content is sent to the provider you selected for that room so it can generate output.',
                'Content sent to a provider is subject to that provider terms and privacy practices, which are outside our control. You should review the terms of any provider you bind, especially regarding how it may retain or use the content it receives.',
            ],
        },
        {
            heading: 'Cookies and analytics',
            body: [
                'We aim to use only essential cookies and minimal analytics needed to run the site and the hosted service, such as keeping you signed in and understanding basic usage at an aggregate level.',
                'We do not engage in invasive cross-site tracking for advertising. If our use of cookies or analytics changes materially, we will update this policy.',
            ],
        },
        {
            heading: 'Data retention',
            body: [
                'We retain account, room, and operational data for as long as needed to provide the service and for legitimate operational, legal, and security purposes. Retention periods may evolve as the product matures out of early access.',
                'When you delete a room or close your account, we will take reasonable steps to remove or de-identify the associated data within a reasonable period, subject to backups and any retention required for legal or security reasons.',
            ],
        },
        {
            heading: 'Data security',
            body: [
                'We design the service around room isolation, so that each room identity, workspace, artifacts, credentials, and runtime state are kept separate from other rooms and tenants. Provider keys and secrets are bound per room and handled with access controls intended to limit exposure to what each room needs.',
                'We apply standard security practices such as encryption in transit, access restrictions, and operational safeguards. We do not claim any specific certification or compliance attestation, and no system can be guaranteed to be fully secure, but we treat isolation and credential handling as central to how the service is built.',
            ],
        },
        {
            heading: 'Your choices and access',
            body: [
                'You can access and update your account information and can delete rooms and their content. You can request that we delete your account, subject to the retention limits described above.',
                'If you want to access, correct, or delete personal data we hold about you, or have questions about how your data is handled, you can contact us through the channel listed on the marketing site.',
            ],
        },
        {
            heading: 'Self-hosted note',
            body: [
                'Agent Room is open source and can be self-hosted. If you self-host, you control your own deployment, infrastructure, and data, and this policy does not apply to that deployment.',
                'In a self-hosted setup, decisions about storage, retention, security, and provider usage are yours, and we do not have access to or responsibility for the data in deployments you operate.',
            ],
        },
        {
            heading: 'Changes to this policy',
            body: [
                'We may update this policy as the product develops, particularly as it leaves early access. When we make material changes, we will update the date on this page and, where appropriate, provide additional notice.',
                'Your continued use of the hosted service after an update takes effect means you accept the updated policy.',
            ],
        },
        {
            heading: 'Security contact',
            body: [
                'If you discover a security or privacy issue, or believe a room credential or secret may have been exposed, please contact us promptly through the channel listed on the marketing site so we can investigate and respond.',
            ],
        },
    ],
}
