/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as RoomsRoomIdIndexRouteImport } from './routes/rooms.$roomId.index'
import { Route as RoomsRoomIdSettingsRouteImport } from './routes/rooms.$roomId.settings'
import { Route as RoomsRoomIdMemoryRouteImport } from './routes/rooms.$roomId.memory'
import { Route as RoomsRoomIdJobsRouteImport } from './routes/rooms.$roomId.jobs'
import { Route as RoomsRoomIdFilesRouteImport } from './routes/rooms.$roomId.files'
import { Route as GithubAppCallbackRouteImport } from './routes/github.app.callback'
import { Route as ApiGithubEventsRouteImport } from './routes/api.github.events'
import { Route as RoomsRoomIdSessionsSessionKeyRouteImport } from './routes/rooms.$roomId.sessions.$sessionKey'
import { Route as ApiRoomsRoomIdEventsRouteImport } from './routes/api.rooms.$roomId.events'
import { Route as ApiRoomsRoomIdFilesUploadRouteImport } from './routes/api.rooms.$roomId.files.upload'
import { Route as ApiRoomsRoomIdFilesPreviewRouteImport } from './routes/api.rooms.$roomId.files.preview'
import { Route as ApiRoomsRoomIdSessionsSessionKeyEventsRouteImport } from './routes/api.rooms.$roomId.sessions.$sessionKey.events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdIndexRoute = RoomsRoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdSettingsRoute = RoomsRoomIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdMemoryRoute = RoomsRoomIdMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdJobsRoute = RoomsRoomIdJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdFilesRoute = RoomsRoomIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const GithubAppCallbackRoute = GithubAppCallbackRouteImport.update({
  id: '/github/app/callback',
  path: '/github/app/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubEventsRoute = ApiGithubEventsRouteImport.update({
  id: '/api/github/events',
  path: '/api/github/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdSessionsSessionKeyRoute =
  RoomsRoomIdSessionsSessionKeyRouteImport.update({
    id: '/sessions/$sessionKey',
    path: '/sessions/$sessionKey',
    getParentRoute: () => RoomsRoomIdRoute,
  } as any)
const ApiRoomsRoomIdEventsRoute = ApiRoomsRoomIdEventsRouteImport.update({
  id: '/api/rooms/$roomId/events',
  path: '/api/rooms/$roomId/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdFilesUploadRoute =
  ApiRoomsRoomIdFilesUploadRouteImport.update({
    id: '/api/rooms/$roomId/files/upload',
    path: '/api/rooms/$roomId/files/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRoomsRoomIdFilesPreviewRoute =
  ApiRoomsRoomIdFilesPreviewRouteImport.update({
    id: '/api/rooms/$roomId/files/preview',
    path: '/api/rooms/$roomId/files/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRoomsRoomIdSessionsSessionKeyEventsRoute =
  ApiRoomsRoomIdSessionsSessionKeyEventsRouteImport.update({
    id: '/api/rooms/$roomId/sessions/$sessionKey/events',
    path: '/api/rooms/$roomId/sessions/$sessionKey/events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/api/github/events': typeof ApiGithubEventsRoute
  '/github/app/callback': typeof GithubAppCallbackRoute
  '/rooms/$roomId/files': typeof RoomsRoomIdFilesRoute
  '/rooms/$roomId/jobs': typeof RoomsRoomIdJobsRoute
  '/rooms/$roomId/memory': typeof RoomsRoomIdMemoryRoute
  '/rooms/$roomId/settings': typeof RoomsRoomIdSettingsRoute
  '/rooms/$roomId/': typeof RoomsRoomIdIndexRoute
  '/api/rooms/$roomId/events': typeof ApiRoomsRoomIdEventsRoute
  '/rooms/$roomId/sessions/$sessionKey': typeof RoomsRoomIdSessionsSessionKeyRoute
  '/api/rooms/$roomId/files/preview': typeof ApiRoomsRoomIdFilesPreviewRoute
  '/api/rooms/$roomId/files/upload': typeof ApiRoomsRoomIdFilesUploadRoute
  '/api/rooms/$roomId/sessions/$sessionKey/events': typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/github/events': typeof ApiGithubEventsRoute
  '/github/app/callback': typeof GithubAppCallbackRoute
  '/rooms/$roomId/files': typeof RoomsRoomIdFilesRoute
  '/rooms/$roomId/jobs': typeof RoomsRoomIdJobsRoute
  '/rooms/$roomId/memory': typeof RoomsRoomIdMemoryRoute
  '/rooms/$roomId/settings': typeof RoomsRoomIdSettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdIndexRoute
  '/api/rooms/$roomId/events': typeof ApiRoomsRoomIdEventsRoute
  '/rooms/$roomId/sessions/$sessionKey': typeof RoomsRoomIdSessionsSessionKeyRoute
  '/api/rooms/$roomId/files/preview': typeof ApiRoomsRoomIdFilesPreviewRoute
  '/api/rooms/$roomId/files/upload': typeof ApiRoomsRoomIdFilesUploadRoute
  '/api/rooms/$roomId/sessions/$sessionKey/events': typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/api/github/events': typeof ApiGithubEventsRoute
  '/github/app/callback': typeof GithubAppCallbackRoute
  '/rooms/$roomId/files': typeof RoomsRoomIdFilesRoute
  '/rooms/$roomId/jobs': typeof RoomsRoomIdJobsRoute
  '/rooms/$roomId/memory': typeof RoomsRoomIdMemoryRoute
  '/rooms/$roomId/settings': typeof RoomsRoomIdSettingsRoute
  '/rooms/$roomId/': typeof RoomsRoomIdIndexRoute
  '/api/rooms/$roomId/events': typeof ApiRoomsRoomIdEventsRoute
  '/rooms/$roomId/sessions/$sessionKey': typeof RoomsRoomIdSessionsSessionKeyRoute
  '/api/rooms/$roomId/files/preview': typeof ApiRoomsRoomIdFilesPreviewRoute
  '/api/rooms/$roomId/files/upload': typeof ApiRoomsRoomIdFilesUploadRoute
  '/api/rooms/$roomId/sessions/$sessionKey/events': typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/billing'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/rooms/$roomId'
    | '/api/github/events'
    | '/github/app/callback'
    | '/rooms/$roomId/files'
    | '/rooms/$roomId/jobs'
    | '/rooms/$roomId/memory'
    | '/rooms/$roomId/settings'
    | '/rooms/$roomId/'
    | '/api/rooms/$roomId/events'
    | '/rooms/$roomId/sessions/$sessionKey'
    | '/api/rooms/$roomId/files/preview'
    | '/api/rooms/$roomId/files/upload'
    | '/api/rooms/$roomId/sessions/$sessionKey/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/api/github/events'
    | '/github/app/callback'
    | '/rooms/$roomId/files'
    | '/rooms/$roomId/jobs'
    | '/rooms/$roomId/memory'
    | '/rooms/$roomId/settings'
    | '/rooms/$roomId'
    | '/api/rooms/$roomId/events'
    | '/rooms/$roomId/sessions/$sessionKey'
    | '/api/rooms/$roomId/files/preview'
    | '/api/rooms/$roomId/files/upload'
    | '/api/rooms/$roomId/sessions/$sessionKey/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/billing'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/rooms/$roomId'
    | '/api/github/events'
    | '/github/app/callback'
    | '/rooms/$roomId/files'
    | '/rooms/$roomId/jobs'
    | '/rooms/$roomId/memory'
    | '/rooms/$roomId/settings'
    | '/rooms/$roomId/'
    | '/api/rooms/$roomId/events'
    | '/rooms/$roomId/sessions/$sessionKey'
    | '/api/rooms/$roomId/files/preview'
    | '/api/rooms/$roomId/files/upload'
    | '/api/rooms/$roomId/sessions/$sessionKey/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRouteWithChildren
  ApiGithubEventsRoute: typeof ApiGithubEventsRoute
  GithubAppCallbackRoute: typeof GithubAppCallbackRoute
  ApiRoomsRoomIdEventsRoute: typeof ApiRoomsRoomIdEventsRoute
  ApiRoomsRoomIdFilesPreviewRoute: typeof ApiRoomsRoomIdFilesPreviewRoute
  ApiRoomsRoomIdFilesUploadRoute: typeof ApiRoomsRoomIdFilesUploadRoute
  ApiRoomsRoomIdSessionsSessionKeyEventsRoute: typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/': {
      id: '/rooms/$roomId/'
      path: '/'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof RoomsRoomIdIndexRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/settings': {
      id: '/rooms/$roomId/settings'
      path: '/settings'
      fullPath: '/rooms/$roomId/settings'
      preLoaderRoute: typeof RoomsRoomIdSettingsRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/memory': {
      id: '/rooms/$roomId/memory'
      path: '/memory'
      fullPath: '/rooms/$roomId/memory'
      preLoaderRoute: typeof RoomsRoomIdMemoryRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/jobs': {
      id: '/rooms/$roomId/jobs'
      path: '/jobs'
      fullPath: '/rooms/$roomId/jobs'
      preLoaderRoute: typeof RoomsRoomIdJobsRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/files': {
      id: '/rooms/$roomId/files'
      path: '/files'
      fullPath: '/rooms/$roomId/files'
      preLoaderRoute: typeof RoomsRoomIdFilesRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/github/app/callback': {
      id: '/github/app/callback'
      path: '/github/app/callback'
      fullPath: '/github/app/callback'
      preLoaderRoute: typeof GithubAppCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/events': {
      id: '/api/github/events'
      path: '/api/github/events'
      fullPath: '/api/github/events'
      preLoaderRoute: typeof ApiGithubEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/sessions/$sessionKey': {
      id: '/rooms/$roomId/sessions/$sessionKey'
      path: '/sessions/$sessionKey'
      fullPath: '/rooms/$roomId/sessions/$sessionKey'
      preLoaderRoute: typeof RoomsRoomIdSessionsSessionKeyRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/api/rooms/$roomId/events': {
      id: '/api/rooms/$roomId/events'
      path: '/api/rooms/$roomId/events'
      fullPath: '/api/rooms/$roomId/events'
      preLoaderRoute: typeof ApiRoomsRoomIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/files/upload': {
      id: '/api/rooms/$roomId/files/upload'
      path: '/api/rooms/$roomId/files/upload'
      fullPath: '/api/rooms/$roomId/files/upload'
      preLoaderRoute: typeof ApiRoomsRoomIdFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/files/preview': {
      id: '/api/rooms/$roomId/files/preview'
      path: '/api/rooms/$roomId/files/preview'
      fullPath: '/api/rooms/$roomId/files/preview'
      preLoaderRoute: typeof ApiRoomsRoomIdFilesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/sessions/$sessionKey/events': {
      id: '/api/rooms/$roomId/sessions/$sessionKey/events'
      path: '/api/rooms/$roomId/sessions/$sessionKey/events'
      fullPath: '/api/rooms/$roomId/sessions/$sessionKey/events'
      preLoaderRoute: typeof ApiRoomsRoomIdSessionsSessionKeyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoomsRoomIdRouteChildren {
  RoomsRoomIdFilesRoute: typeof RoomsRoomIdFilesRoute
  RoomsRoomIdJobsRoute: typeof RoomsRoomIdJobsRoute
  RoomsRoomIdMemoryRoute: typeof RoomsRoomIdMemoryRoute
  RoomsRoomIdSettingsRoute: typeof RoomsRoomIdSettingsRoute
  RoomsRoomIdIndexRoute: typeof RoomsRoomIdIndexRoute
  RoomsRoomIdSessionsSessionKeyRoute: typeof RoomsRoomIdSessionsSessionKeyRoute
}

const RoomsRoomIdRouteChildren: RoomsRoomIdRouteChildren = {
  RoomsRoomIdFilesRoute: RoomsRoomIdFilesRoute,
  RoomsRoomIdJobsRoute: RoomsRoomIdJobsRoute,
  RoomsRoomIdMemoryRoute: RoomsRoomIdMemoryRoute,
  RoomsRoomIdSettingsRoute: RoomsRoomIdSettingsRoute,
  RoomsRoomIdIndexRoute: RoomsRoomIdIndexRoute,
  RoomsRoomIdSessionsSessionKeyRoute: RoomsRoomIdSessionsSessionKeyRoute,
}

const RoomsRoomIdRouteWithChildren = RoomsRoomIdRoute._addFileChildren(
  RoomsRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  RoomsRoomIdRoute: RoomsRoomIdRouteWithChildren,
  ApiGithubEventsRoute: ApiGithubEventsRoute,
  GithubAppCallbackRoute: GithubAppCallbackRoute,
  ApiRoomsRoomIdEventsRoute: ApiRoomsRoomIdEventsRoute,
  ApiRoomsRoomIdFilesPreviewRoute: ApiRoomsRoomIdFilesPreviewRoute,
  ApiRoomsRoomIdFilesUploadRoute: ApiRoomsRoomIdFilesUploadRoute,
  ApiRoomsRoomIdSessionsSessionKeyEventsRoute:
    ApiRoomsRoomIdSessionsSessionKeyEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
