/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as RoomsRoomIdStatusRouteImport } from './routes/rooms.$roomId.status'
import { Route as RoomsRoomIdSettingsRouteImport } from './routes/rooms.$roomId.settings'
import { Route as RoomsRoomIdJobsRouteImport } from './routes/rooms.$roomId.jobs'
import { Route as RoomsRoomIdFilesRouteImport } from './routes/rooms.$roomId.files'
import { Route as RoomsRoomIdSessionsSessionKeyRouteImport } from './routes/rooms.$roomId.sessions.$sessionKey'
import { Route as ApiRoomsRoomIdSessionsSessionKeyEventsRouteImport } from './routes/api.rooms.$roomId.sessions.$sessionKey.events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdStatusRoute = RoomsRoomIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdSettingsRoute = RoomsRoomIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdJobsRoute = RoomsRoomIdJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdFilesRoute = RoomsRoomIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdSessionsSessionKeyRoute =
  RoomsRoomIdSessionsSessionKeyRouteImport.update({
    id: '/sessions/$sessionKey',
    path: '/sessions/$sessionKey',
    getParentRoute: () => RoomsRoomIdRoute,
  } as any)
const ApiRoomsRoomIdSessionsSessionKeyEventsRoute =
  ApiRoomsRoomIdSessionsSessionKeyEventsRouteImport.update({
    id: '/api/rooms/$roomId/sessions/$sessionKey/events',
    path: '/api/rooms/$roomId/sessions/$sessionKey/events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/files': typeof RoomsRoomIdFilesRoute
  '/rooms/$roomId/jobs': typeof RoomsRoomIdJobsRoute
  '/rooms/$roomId/settings': typeof RoomsRoomIdSettingsRoute
  '/rooms/$roomId/status': typeof RoomsRoomIdStatusRoute
  '/rooms/$roomId/sessions/$sessionKey': typeof RoomsRoomIdSessionsSessionKeyRoute
  '/api/rooms/$roomId/sessions/$sessionKey/events': typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/files': typeof RoomsRoomIdFilesRoute
  '/rooms/$roomId/jobs': typeof RoomsRoomIdJobsRoute
  '/rooms/$roomId/settings': typeof RoomsRoomIdSettingsRoute
  '/rooms/$roomId/status': typeof RoomsRoomIdStatusRoute
  '/rooms/$roomId/sessions/$sessionKey': typeof RoomsRoomIdSessionsSessionKeyRoute
  '/api/rooms/$roomId/sessions/$sessionKey/events': typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/files': typeof RoomsRoomIdFilesRoute
  '/rooms/$roomId/jobs': typeof RoomsRoomIdJobsRoute
  '/rooms/$roomId/settings': typeof RoomsRoomIdSettingsRoute
  '/rooms/$roomId/status': typeof RoomsRoomIdStatusRoute
  '/rooms/$roomId/sessions/$sessionKey': typeof RoomsRoomIdSessionsSessionKeyRoute
  '/api/rooms/$roomId/sessions/$sessionKey/events': typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/files'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/rooms/$roomId'
    | '/rooms/$roomId/files'
    | '/rooms/$roomId/jobs'
    | '/rooms/$roomId/settings'
    | '/rooms/$roomId/status'
    | '/rooms/$roomId/sessions/$sessionKey'
    | '/api/rooms/$roomId/sessions/$sessionKey/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/files'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/rooms/$roomId'
    | '/rooms/$roomId/files'
    | '/rooms/$roomId/jobs'
    | '/rooms/$roomId/settings'
    | '/rooms/$roomId/status'
    | '/rooms/$roomId/sessions/$sessionKey'
    | '/api/rooms/$roomId/sessions/$sessionKey/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/files'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/rooms/$roomId'
    | '/rooms/$roomId/files'
    | '/rooms/$roomId/jobs'
    | '/rooms/$roomId/settings'
    | '/rooms/$roomId/status'
    | '/rooms/$roomId/sessions/$sessionKey'
    | '/api/rooms/$roomId/sessions/$sessionKey/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRouteWithChildren
  ApiRoomsRoomIdSessionsSessionKeyEventsRoute: typeof ApiRoomsRoomIdSessionsSessionKeyEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/status': {
      id: '/rooms/$roomId/status'
      path: '/status'
      fullPath: '/rooms/$roomId/status'
      preLoaderRoute: typeof RoomsRoomIdStatusRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/settings': {
      id: '/rooms/$roomId/settings'
      path: '/settings'
      fullPath: '/rooms/$roomId/settings'
      preLoaderRoute: typeof RoomsRoomIdSettingsRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/jobs': {
      id: '/rooms/$roomId/jobs'
      path: '/jobs'
      fullPath: '/rooms/$roomId/jobs'
      preLoaderRoute: typeof RoomsRoomIdJobsRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/files': {
      id: '/rooms/$roomId/files'
      path: '/files'
      fullPath: '/rooms/$roomId/files'
      preLoaderRoute: typeof RoomsRoomIdFilesRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/sessions/$sessionKey': {
      id: '/rooms/$roomId/sessions/$sessionKey'
      path: '/sessions/$sessionKey'
      fullPath: '/rooms/$roomId/sessions/$sessionKey'
      preLoaderRoute: typeof RoomsRoomIdSessionsSessionKeyRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/api/rooms/$roomId/sessions/$sessionKey/events': {
      id: '/api/rooms/$roomId/sessions/$sessionKey/events'
      path: '/api/rooms/$roomId/sessions/$sessionKey/events'
      fullPath: '/api/rooms/$roomId/sessions/$sessionKey/events'
      preLoaderRoute: typeof ApiRoomsRoomIdSessionsSessionKeyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoomsRoomIdRouteChildren {
  RoomsRoomIdFilesRoute: typeof RoomsRoomIdFilesRoute
  RoomsRoomIdJobsRoute: typeof RoomsRoomIdJobsRoute
  RoomsRoomIdSettingsRoute: typeof RoomsRoomIdSettingsRoute
  RoomsRoomIdStatusRoute: typeof RoomsRoomIdStatusRoute
  RoomsRoomIdSessionsSessionKeyRoute: typeof RoomsRoomIdSessionsSessionKeyRoute
}

const RoomsRoomIdRouteChildren: RoomsRoomIdRouteChildren = {
  RoomsRoomIdFilesRoute: RoomsRoomIdFilesRoute,
  RoomsRoomIdJobsRoute: RoomsRoomIdJobsRoute,
  RoomsRoomIdSettingsRoute: RoomsRoomIdSettingsRoute,
  RoomsRoomIdStatusRoute: RoomsRoomIdStatusRoute,
  RoomsRoomIdSessionsSessionKeyRoute: RoomsRoomIdSessionsSessionKeyRoute,
}

const RoomsRoomIdRouteWithChildren = RoomsRoomIdRoute._addFileChildren(
  RoomsRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  RoomsRoomIdRoute: RoomsRoomIdRouteWithChildren,
  ApiRoomsRoomIdSessionsSessionKeyEventsRoute:
    ApiRoomsRoomIdSessionsSessionKeyEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
