use_default_settings:
    engines:
        remove:
            - ahmia
            - torch
            - wikidata

general:
    instance_name: Agent Room Search

search:
    formats:
        - html
        - json
    safe_search: 0

server:
    limiter: false
    public_instance: false
    secret_key: agent-room-local-search
